### ISSUE TITLE
Button to create a report

### ISSUE THREAD

**Issue by parsiya** [parsiya/bug-diaries#3]
1. We need to convert all the issues to XML.
2. Use the following XSLT to generate an HTML report.
    * https://gist.github.com/pajswigger/32c5255147ac0489241ac60b406a4506
    * My fork in case it needs modification: https://gist.github.com/parsiya/889cf911600a9826dbbbc3dbf42bb9c7

### Tasks

* [ ] Figure out how to convert the issues to XML. No need to convert from JSON. Object to XML works.
* [ ] Figure out how to use the XSLT above to generate a report.
    * [ ] I remember there were some bugs when I did it manually,
* [x] Add a new button to make a report.
* [ ] Add it to the documentation

**Use [IBurpExtenderCallbacks.generateScanReport](https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#generateScanReport(java.lang.String,%20burp.IScanIssue[],%20java.io.File))**
* [x] Does it make the extension only work in pro version? If so, will not work for us.
    * Only works in the pro version.
* [x] Get it to work on the pro version.
     * Works in the pro version
* [x] Try it in the free version to see if it works or not, probably not but worth a try.
    * Does not work in the free version. seems like we have to use the XSLT then.

**Comment by parsiya** [comment]
* [ ] Figure out how to convert the issues from JSON to XML. Does gson help or do we have to use a separate file?
* [ ] Figure out how to use the XSLT above to generate a report.
    * [ ] I remember there were some bugs when I did it manually,
* [ ] Add a new button to make a report.
* [ ] Add it to the documentation

**Comment by parsiya** [comment]
Alternatively, I could convert the bugs to Burp Issues and use [IBurpExtenderCallbacks.generateScanReport](https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#generateScanReport(java.lang.String,%20burp.IScanIssue[],%20java.io.File))

* [ ] Does it make the extension only work in pro version? If so, will not work for us.

**Comment by parsiya** [comment]
This involves adding new fields to `Bug` and the GUI. The `type` thing is going to be hard to figure out without asking the user to create it. I could have an internal DB that maps finding names to it (will work for adding CWEs) but other than that we have to add it manually.

More here:
* https://portswigger.net/burp/documentation/desktop/scanning/reporting-results

**Comment by parsiya** [comment]
Being tracked in the issue3 branch. Currently, generate report silently fails in both the pro and the community versions.

**Comment by parsiya** [comment]
Thanks to Burp's twitter account, we need to run it with `--diagnostics` flag.
Appears to be a pro version feature. My issue was that severity and confidence must be one of the few values and they are case-sensitive. If they are not one of the valid values, we get an error and it silently failed.

**Comment by parsiya** [comment]
* [ ] Get it to work on the pro version.
* [ ] Try it in the free version to see if it works or not, probably not but worth a try.
